name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ make libsqlite3-dev lcov libcunit1-dev

    - name: Create Database
      run: make db

    - name: Build and Test
      run: make test

    - name: Generate Coverage Report
      run: make coverage

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/
        files: coverage.info
        fail_ci_if_error: true
        verbose: true
